require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Aksbha' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  target 'AksbhaTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'Aksbha-tvOS' do
  # Pods for Aksbha-tvOS

  target 'Aksbha-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
